# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_image_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.ImageField(upload_to='diets/'),
        ),
    ]
