# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_auto_20190417_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
